
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: EMBEDDED
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 1
          max-idle: 8
          max-active: 8
          max-wait: 3000




mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true


im:
  server:
    configuration:
      model: host
      zookeeper:
        servers: 127.0.0.1:2181
        sessionTimeout: 3000
    host: 172.30.112.1
    port: 2921
