
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 1
          max-idle: 8
          max-active: 8
          max-wait: 3000


im:
  web:
    url: http://localhost:9090
    apikey: 26662f07703c41d2a4994b8b30b101a9
  server:
    configuration:
      model: cluster
      zookeeper:
        servers: 127.0.0.1:2181
        sessionTimeout: 3000
    host: 172.30.112.1
    port: 2921
