server:
  port: 9090

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          min-idle: 1
          max-idle: 8
          max-active: 8
          max-wait: 3000
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
    suffix: .html
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    port: 587
    username: 1085385084@qq.com
    password: bwmuexbfttocibja
    from: 1085385084@qq.com


logging:
  level:
    org.springframework.security: trace

zookeeper:
  servers: 127.0.0.1:2181
  sessionTimeout: 3000

minio:
  endpoint: http://127.0.0.1:9000
  bucketName: y-chat-bucket
  accessKey: ldpiqxlrXrEtNB8SF79W
  secretKey: 7rfOUvkNu6ofE9VPWZj2w5V1rcanVGmNXNPNyl5j

mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true


auth:
  coexistToken: 1
  jwt:
    secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    # 单位：s:秒 m:分钟 h:小时 d:天 默认 秒
    expiration: 24h
    refreshExpiration: 30d
  rememberMe:
    secretKey: 209E335266556A586E3272357538782F413A4428472B4B6250645367566B5B76
    # 单位：s:秒 m:分钟 h:小时 d:天 默认 秒
    expiration: 7d
  other-login:
    self:
      clientName: Self
      clientId: 32b00b1e89af-90d2e0e46d20ebb92f6c
      clientSecret: 123456
      redirectUrl: http://localhost:3000/login
      scope: userInfo+openid
      authCodeUrl: http://127.0.0.1:9090/oauth2/authorize?client_id=${auth.other-login.self.clientId}&scope=${auth.other-login.self.scope}&redirect_uri=${auth.other-login.self.redirectUrl}&response_type=code&state=Self
      deviceCodeUrl: http://127.0.0.1:9090/oauth2/device_authorization?client_id=${auth.other-login.self.clientId}&client_secret=${auth.other-login.self.clientSecret}&scope=userInfo
      tokenUrl: http://127.0.0.1:9090/oauth2/token
      userInfoUrl: http://127.0.0.1:9090/userinfo
    github:
      clientName: Github
      clientId: xxx
      clientSecret: xxxx
      redirectUrl: http://localhost:3000/login
      scope: user
      authCodeUrl: https://github.com/login/oauth/authorize?client_id=${auth.other-login.github.clientId}&redirect_uri=${auth.other-login.github.redirectUrl}&scope=${auth.other-login.github.scope}&state=Github
      tokenUrl: https://github.com/login/oauth/access_token
      userInfoUrl: https://api.github.com/user
      userEmailsUrl: https://api.github.com/user/emails
    google:
      clientName: Google
      clientId: xxx
      clientSecret: xxx
      redirectUrl: http://localhost:3000/login
      scope: https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile+openid
      authCodeUrl: https://accounts.google.com/o/oauth2/v2/auth?client_id=${auth.other-login.google.clientId}&redirect_uri=${auth.other-login.google.redirectUrl}&scope=${auth.other-login.google.scope}&response_type=code&access_type=offline&prompt=consent&state=Google
      tokenUrl: https://oauth2.googleapis.com/token
      userInfoUrl: https://www.googleapis.com/oauth2/v3/userinfo
    microsoft:
      clientName: Microsoft
      clientId: xxx
      clientSecret: xxx
      tenantId: c719f474-19d6-42af-a36f-1f264ac08653
      redirectUrl: http://localhost:3000/login
      scope: https://graph.microsoft.com/User.Read
      authCodeUrl: https://login.microsoftonline.com/${auth.other-login.microsoft.tenantId}/oauth2/v2.0/authorize?client_id=${auth.other-login.microsoft.clientId}&client_secret=${auth.other-login.microsoft.clientSecret}&redirect_uri=${auth.other-login.microsoft.redirectUrl}&scope=${auth.other-login.microsoft.scope}&response_type=code&state=Microsoft
      tokenUrl: https://login.microsoftonline.com/${auth.other-login.microsoft.tenantId}/oauth2/v2.0/token
      userInfoUrl: https://graph.microsoft.com/oidc/userinfo



http:
  config:
    # 单位：秒
    connectionRequestTimeout: 5
    responseTimeout: 60
    proxy: 'http://127.0.0.1:1081'
